# Generated by Django 3.2 on 2023-11-25 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='confirm',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=20),
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.IntegerField(max_length=100),
        ),
    ]
